// TEMPORARY lint config for the modularization refactor. Safe to delete.
const browserGlobals = {
    window: 'readonly',
    document: 'readonly',
    localStorage: 'readonly',
    sessionStorage: 'readonly',
    navigator: 'readonly',
    location: 'readonly',
    history: 'readonly',
    fetch: 'readonly',
    URL: 'readonly',
    URLSearchParams: 'readonly',
    Blob: 'readonly',
    File: 'readonly',
    FileReader: 'readonly',
    FormData: 'readonly',
    CSS: 'readonly',
    Intl: 'readonly',
    console: 'readonly',
    setTimeout: 'readonly',
    clearTimeout: 'readonly',
    setInterval: 'readonly',
    clearInterval: 'readonly',
    requestAnimationFrame: 'readonly',
    cancelAnimationFrame: 'readonly',
    Image: 'readonly',
    alert: 'readonly',
    confirm: 'readonly',
    prompt: 'readonly',
    atob: 'readonly',
    btoa: 'readonly',
    structuredClone: 'readonly',
    TextEncoder: 'readonly',
    TextDecoder: 'readonly',
    AbortController: 'readonly',
    getComputedStyle: 'readonly',
    MutationObserver: 'readonly',
    ResizeObserver: 'readonly',
    // CDN-Globals
    Chart: 'readonly',
    Hammer: 'readonly',
    globalThis: 'readonly',
};

export default [
    {
        files: ['static/cursor-analytics/**/*.js'],
        languageOptions: {
            ecmaVersion: 'latest',
            sourceType: 'module',
            globals: browserGlobals,
        },
        rules: {
            'no-undef': 'error',
            'no-import-assign': 'error',
            'no-redeclare': 'error',
            'no-dupe-keys': 'error',
            'no-dupe-args': 'error',
            'no-unused-vars': ['warn', { args: 'none', varsIgnorePattern: '^_' }],
        },
    },
];
